### ISSUE TITLE
can`t rename default mqtt topic

### ISSUE THREAD

**Issue by vpaulos** [bilan/connectlife-api-connector#27] opened 2024-05-06 20:06 UTC
By default , addon connect and out info from|to topic named "core-mosquito"
can you add into config possibilities to change the name of topic?

![image](https://github.com/bilan/connectlife-api-connector/assets/48480823/06bd677a-7878-40e3-82e1-210863615860)

**Comment by bilan** [comment] 2024-05-07 11:52
I'm not sure if I understand what the problem is.

If you click on the device you will be able to change its name. The icon will be in the top right corner.

**Closed** 2024-06-01 10:40 UTC
